from flask import jsonify

import src.mysql as mysql

class JmartResourse:
    def sku_get(shop_name, sku):
        if shop_name == 'protel':
            return mysql.Jmart.search(sku)
        elif shop_name == 'don_phone':
            return mysql.JmartDon.search(sku)
        elif shop_name == 'mil_phone':
            return mysql.JmartMil.search(sku)


    def sku_delete(shop_name, sku):
        if shop_name == 'protel':
            mysql.Jmart.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'don_phone':
            mysql.JmartDon.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'mil_phone':
            mysql.JmartMil.delete(sku)
            return jsonify('Удалено успешно')

    def sku_put(shop_name, parser, sku):
        if shop_name == 'protel':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.Jmart.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'don_phone':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.JmartDon.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'mil_phone':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.JmartMil.update = parser.parse_args()
            return jsonify('Обновлено успешно')

    def get(shop_name):
        if shop_name == 'protel':
            return mysql.Jmart.get()
        elif shop_name == 'don_phone':
            return mysql.JmartDon.get()
        elif shop_name == 'mil_phone':
            return mysql.JmartMil.get()

    def post(shop_name, parser):
        if shop_name == 'protel':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.Jmart.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'don_phone':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.JmartDon.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'mil_phone':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('brand', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.JmartMil.add = parser.parse_args()
            return jsonify('Добавлено успешно')