from flask import jsonify

import src.mysql as mysql


class HalykResourse:
    def sku_get(shop_name, sku):
        if shop_name == 'georgopol':
            return mysql.HalykGeorgopol.search(sku)
        elif shop_name == 'one_phone':
            return mysql.HalykOnePhone.search(sku)
        elif shop_name == 'yess_tell':
            return mysql.HalykYessTell.search(sku)
        elif shop_name == 'protel':
            return mysql.HalykProtel.search(sku)
        elif shop_name == 'ani_tell':
            return mysql.HalykAniTell.search(sku)
        elif shop_name == 'bubble_phone':
            return mysql.HalykBubblePhone.search(sku)
        elif shop_name == 'megamobile':
            return mysql.HalykMegaMobile.search(sku)
        elif shop_name == 'smartpoint':
            return mysql.HalykSmartpoint.search(sku)
        elif shop_name == 'zu_phone':
            return mysql.HalykZuPhone.search(sku)

    def sku_delete(shop_name, sku):
        if shop_name == 'georgopol':
            mysql.HalykGeorgopol.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'one_phone':
            mysql.HalykOnePhone.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'yess_tell':
            mysql.HalykYessTell.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'protel':
            mysql.HalykProtel.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'ani_tell':
            mysql.HalykAniTell.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'bubble_phone':
            mysql.HalykBubblePhone.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'megamobile':
            mysql.HalykMegaMobile.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'smartpoint':
            mysql.HalykSmartpoint.delete(sku)
            return jsonify('Удалено успешно')
        elif shop_name == 'zu_phone':
            mysql.HalykZuPhone.delete(sku)
            return jsonify('Удалено успешно')

    def sku_put(shop_name, parser, sku):
        if shop_name == 'georgopol':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykGeorgopol.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'one_phone':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykOnePhone.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'yess_tell':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykYessTell.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'protel':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykProtel.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'ani_tell':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            mysql.HalykAniTell.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'bubble_phone':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            mysql.HalykBubblePhone.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'megamobile':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykMegaMobile.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'smartpoint':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykSmartpoint.update = parser.parse_args()
            return jsonify('Обновлено успешно')
        elif shop_name == 'zu_phone':
            parser.add_argument(f'{sku}', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            mysql.HalykZuPhone.update = parser.parse_args()
            return jsonify('Обновлено успешно')
            
    def get(shop_name):
        if shop_name == 'georgopol':
            return mysql.HalykGeorgopol.get()
        elif shop_name == 'one_phone':
            return mysql.HalykOnePhone.get()
        elif shop_name == 'yess_tell':
            return mysql.HalykYessTell.get()
        elif shop_name == 'protel':
            return mysql.HalykProtel.get()
        elif shop_name == 'ani_tell':
            return mysql.HalykAniTell.get()
        elif shop_name == 'bubble_phone':
            return mysql.HalykBubblePhone.get()
        elif shop_name == 'megamobile':
            return mysql.HalykMegaMobile.get()
        elif shop_name == 'smartpoint':
            return mysql.HalykSmartpoint.get()
        elif shop_name == 'zu_phone':
            return mysql.HalykZuPhone.get()

    def post(shop_name, parser):
        if shop_name == 'protel':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykProtel.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'one_phone':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykOnePhone.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'yess_tell':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykYessTell.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'georgopol':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            mysql.HalykGeorgopol.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'ani_tell':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            mysql.HalykAniTell.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'bubble_phone':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            mysql.HalykBubblePhone.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'megamobile':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp5', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp11', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp13', type=str)
            parser.add_argument('pp14', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykMegaMobile.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'smartpoint':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            parser.add_argument('pp6', type=str)
            parser.add_argument('pp7', type=str)
            parser.add_argument('pp8', type=str)
            parser.add_argument('pp9', type=str)
            parser.add_argument('pp10', type=str)
            parser.add_argument('pp12', type=str)
            parser.add_argument('pp15', type=str)
            parser.add_argument('pp16', type=str)
            mysql.HalykSmartpoint.add = parser.parse_args()
            return jsonify('Добавлено успешно')
        elif shop_name == 'zu_phone':
            parser.add_argument('sku', type=str)
            parser.add_argument('product_name', type=str)
            parser.add_argument('price', type=str)
            parser.add_argument('loan_period', type=str)
            parser.add_argument('pp1', type=str)
            parser.add_argument('pp2', type=str)
            parser.add_argument('pp3', type=str)
            parser.add_argument('pp4', type=str)
            mysql.HalykZuPhone.add = parser.parse_args()
            return jsonify('Добавлено успешно')